txt = {
	gameName	= "Shmupacabra",
	gameOver	= "Game Over",
	mission1	= "Mission 1",
	mission2	= "Mission 2",
	mission3	= "Final Mission",
	tutorial	= "Tutorial",
	beginning	= "Beginning",
	continue	= "Continue",
	warning		= "Warning",
	success		= "Success",
	victory		= "Victory",
	theEnd		= "The End",
	paused		= "Paused",
	setup		= "Setup",
	start		= "Start",
	retry		= "Retry",
	resume		= "Resume",
	quit		= "Quit",

	eol		= "End of the Line",
	thankYou	= "Thank you for playing!",

	pressPause	= "Press PAUSE...",
	pressCharge	= "Press CHARGE...",
	pressShoot	= "Press SHOOT...",
	pressRight	= "Press RIGHT...",
	pressLeft	= "Press LEFT...",
	pressDown	= "Press DOWN...",
	pressUp		= "Press UP...",

	tutorial0	= "Use SHOOT, SPACE or ENTER to skip text.",
	tutorial1	= "Using direction controls will move you around.",
	tutorial2	= "Tapping SHOOT button will fire spread shot.",
	tutorial3	= "Holding down SHOOT button will fire beam shot.",
	tutorial4	= "Beam shot will slow down your movement.",
	tutorial5	= "Shoot enemies or avoid crashing into them.",
	tutorial6	= "Collecting stars will get you extra lives.",
	tutorial7	= "Do not allow bullets to hit your cockpit.",
	tutorial8	= "Using CHARGE will annihilate enemy bullets.",
	tutorial8b	= "Charging grants short period of invincibility.",
	tutorial9	= "It will take some time for CHARGE to recharge.",
	tutorialX	= "Good Luck!",

	motd		= {
		"You will die.",		-- Cold Fact
		"War is peace.",		-- Orwell
		"You will be killed.",		-- Fact
		"All war is deception.",	-- Sun Tzu
		"Are you brave enough?",	-- Question
		"Do you have what it takes?",	-- Sincere Question
		"Your blood will be spilled.",	-- Heartily Promise
		"Prepare to be annihilated.",	-- Friendly Tip
		"Defeat is inevitable.",	-- Fact
		"Beware of programmer art!",	-- Tip
	},
	loose		= {
		"Better luck next time.",
		"Persistence will be rewarded.",
		"Giving up would not be forgiven.",
		"In Soviet Russia game beats you!",
		"Are you going to leave it like that?",
		"Every time you give up, a kitten dies.",
		"If you give up now, lots of people will die.",
		"Every failure is a step closer to success.",
		"Practice makes perfect.",
		"Failure is temporary.",
		"Take a deep breath.",
		"Life is not easy.",
		"You were killed.",
		"Don't give up!",
		"Don't panic!",
		"You are dead.",
		"Shit happens.",
		"Try again!",
		"Damn it!",
	},
	story1		= {
		"Sometime in the future...",
		"",
		"There is terror wrought upon your planet.",
		"There are blackouts in all major cities.",
		"There is famine and fear everywhere.",
		"",
		"...and the time has come to fight back.",
	},
	story2		= {
		"The battle rages on all throughout the night.",
		"By morning you are so exhausted",
		"that you must take a pill to press on.",
		"The sun is rising as you ascend into the clouds.",
		"The beauty of the sunrise makes you forget your doubts.",
		"Suddenly, a huge shadow passes over you...",
	},
	story3		= {
		"Your body is soaked in sweat and your eyes are bloodshot.",
		"Exhaustion makes you want to give up, "
			.. "but you continue to ascend.",
		"Suddenly you are free from your planet's gravitational pull.",
		"Strange peace and calmness takes over your mind and body.",
		"You know that this feeling will not last long.",
		"The time has come to make history...",
	},
	storyEnd	= {
		"Congratulations!",
		"----------------",
		"",
		"",
		"",
		"    After a hard and exhausting battle you have      ",
		"    single-handedly defeated the entire enemy fleet. ",
		"    With its power core destroyed evil forces        ",
		"    will never be able to attack your planet again.  ",
		"    For your people you are a hero forever.          "
	},
	credits		= {
		" Game by              ",
		"----------------------",
		"    Artūrs Grebstelis ",
		"",
		"",
		"",
		" Engine by            ",
		"----------------------",
		"       Atis Grīnbergs ",
		"",
		"",
		"",
		" Music by             ",
		"----------------------",
		"            Toms Miks ",
		"",
		"",
		"",
		" Special Thanks to    ",
		"----------------------",
		"            Spicausis ",
		"             Lauraiss ",
		"               Sīkais ",
		"               Kovacs ",
		"                Noah! ",
	},
}
return txt
